# Generated by Django 5.2 on 2026-03-05 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=255)),
                ('website_url', models.URLField()),
                ('official_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('incorporation_certificate', models.FileField(upload_to='company_certificates/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
