# Generated by Django 5.2 on 2026-03-05 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_companyverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyverification',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
    ]
