# Generated by Django 5.2 on 2026-03-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_alter_companyverification_employer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyverification',
            options={'ordering': ['-created_at']},
        ),
    ]
