# Generated by Django 5.2 on 2026-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_alter_companyverification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyverification',
            name='registration_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='companyverification',
            name='tax_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
