# Generated by Django 5.2 on 2026-03-10 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_company_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('industry_type', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('work_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('On-site', 'On-site')], max_length=20)),
                ('shift', models.CharField(choices=[('General', 'General'), ('Night', 'Night'), ('Rotational', 'Rotational')], max_length=20)),
                ('work_duration', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Max Annual CTC in LPA', max_digits=10)),
                ('experience', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('openings', models.PositiveIntegerField()),
                ('job_category', models.CharField(choices=[('Full-time', 'Full-time'), ('Internship', 'Internship')], max_length=20)),
                ('education', models.CharField(max_length=255)),
                ('key_skills', models.JSONField()),
                ('job_highlights', models.JSONField()),
                ('job_description', models.TextField()),
                ('responsibilities', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_jobs', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post a Job',
                'verbose_name_plural': 'Post Jobs',
            },
        ),
    ]
