# Generated by Django 5.2 on 2026-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_postajob_delete_postjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
